//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chess.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class GamePartHistory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GamePartHistory()
        {
            this.Turn = new HashSet<Turn>();
        }
    
        public long GamePartHistoryID { get; set; }
        public Nullable<long> GamePartID { get; set; }
    
        public virtual GamePart GamePart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Turn> Turn { get; set; }
    }
}
