//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chess.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class GamePart
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GamePart()
        {
            this.GamePartHistory = new HashSet<GamePartHistory>();
        }
    
        public long GamePartID { get; set; }
        public string GamePartLabel { get; set; }
        public Nullable<System.DateTime> GamePartStartDateTime { get; set; }
        public Nullable<long> GamePartDuration { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GamePartHistory> GamePartHistory { get; set; }
    }
}
